version: '3.8'

services:
  eurostar-snap-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eurostar-snap-alert
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./debug:/app/debug
